"""Demandes des élus locaux (assets/data/events/local.json) et leurs courriers (dialogue/fr/local.json).

Chaque demande : un événement (probabilité selon l'état du territoire), un courrier propre au sujet,
rédigé dans le style de l'élu, et des options aux conséquences différentes (projet financé,
version réduite, report, refus...). Les montants sont en milliards d'euros (0.02 = 20 M€).
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dialogue_fr_lib import V, letter

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "assets", "data")
G = "opinion.group."


def E(target, amount=0.0, param=None, factor=1.0, days=0.0):
    d = {"target": target}
    if param: d["param"] = param; d["factor"] = factor
    else: d["amount"] = amount
    if days: d["days"] = days
    return d


def mod(var, frm, to, fa, fb):
    return {"variable": var, "from": frm, "to": to, "factorAtFrom": fa, "factorAtTo": fb}


def project(name, kind, days, factor, completion):
    return {"name": name, "kind": kind, "durationDays": days, "costParam": "amount", "costFactor": factor, "onCompletion": completion}


def fund_options(name, kind, days, completion, labels=None, refuse_cost=0.02, groups=(), partial=True, reask=45):
    """Options standard d'une demande de financement."""
    L = {"accept": "Financer le projet", "partial": "Financer une version réduite", "postpone": "Reporter la décision",
         "refuse": "Refuser", "details": "Demander des précisions"}
    L.update(labels or {})
    small = [dict(e, amount=round(e.get("amount", 0) / 2, 4)) if "amount" in e else e for e in completion]
    opts = [{"id": "accept", "label": L["accept"], "hint": "Coût : {amountText}, travaux sur plusieurs mois",
             "effects": [E("sender.relation", 0.15), E("scope.approval", 0.025, days=20)] + [E(G + g, 0.002) for g in groups],
             "outcome": "ACCEPTED", "project": project(name, kind, days, 1.0, completion)}]
    if partial:
        opts.append({"id": "partial", "label": L["partial"], "hint": "Coût : la moitié, effets plus modestes",
                     "effects": [E("sender.relation", 0.05), E("scope.approval", 0.01, days=20)],
                     "outcome": "PARTIAL", "project": project(name + " (version réduite)", kind, int(days * 1.2), 0.5, small)})
    opts += [
        {"id": "postpone", "label": L["postpone"], "hint": f"La demande reviendra dans {reask} jours",
         "effects": [E("sender.relation", -0.03)], "outcome": "POSTPONED", "reaskAfterDays": reask},
        {"id": "refuse", "label": L["refuse"], "hint": "Aucun coût, mais mécontentement local",
         "effects": [E("sender.relation", -0.12), E("scope.approval", -refuse_cost, days=10)] + [E(G + g, -0.002) for g in groups],
         "outcome": "REFUSED"},
    ]
    return opts


def request(id, scope, sender, headline, prob, amount, modifiers, template, options, category="TERRITORY",
            cooldown=10, scope_cooldown=400, max_rank=3, days=7, scale=None, conditions=(), default="refuse"):
    p = {"name": "amount", "min": amount[0], "max": amount[1], "round": 0.005}
    if scale: p.update({"scaleBy": "scope.populationMillions", "minScale": 0.3})
    ev = {"id": id, "category": category, "scope": scope, "baseDailyProbability": prob, "cooldownDays": cooldown,
          "scopeCooldownDays": scope_cooldown, "headline": headline, "modifiers": modifiers, "params": [p],
          "message": {"template": template["id"], "sender": sender, "responseDays": days, "defaultOption": default, "options": options}}
    if scope == "CITY": ev["maxCityRank"] = max_rank
    if conditions: ev["conditions"] = list(conditions)
    return ev, template


EVENTS, TEMPLATES = [], []
def add(pair):
    EVENTS.append(pair[0]); TEMPLATES.append(pair[1])

# Probabilités de base : par territoire candidat et par jour (96 départements, ~50 villes).
DEPT = 0.00018
CITY = 0.00030

# ------------------------------------------------------------------------------------------------
add(request("school_renovation", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Collèges vétustes {departmentIn} : le département demande l'aide de l'État",
 DEPT, (0.02, 0.06), [mod("quality.education", 0.4, 0.7, 1.6, 0.7)],
 letter("school_renovation",
  [V("Rénovation des collèges {departmentOf}"), V("Collèges vétustes : appel à l'État"), V("Nos collégiens méritent mieux"),
   V("Plan collèges {departmentOf} : demande de soutien"), V("Bâtiments scolaires : la situation {departmentOf}")],
  [V("Plusieurs collèges {departmentOf} datent des années soixante-dix et n'ont jamais été rénovés en profondeur."),
   V("Toitures qui fuient, chauffage défaillant, sanitaires hors d'usage : l'état de nos collèges n'est plus acceptable."),
   V("La rentrée s'est faite dans des bâtiments où il faisait {{douze|treize}} degrés en salle de classe.", when=["season:autumn"]),
   V("Cet hiver, des cours ont dû être annulés faute de chauffage.", when=["season:winter"]),
   V("Avec la canicule, certaines salles dépassent trente-cinq degrés : les élèves ne peuvent plus travailler.", when=["season:summer"]),
   V("Les parents d'élèves {{multiplient les pétitions|ont manifesté devant la préfecture}} pour dénoncer l'état des établissements."),
   V("Nos équipes techniques ont recensé {{une quinzaine|une vingtaine}} de collèges nécessitant des travaux lourds.", when=["voice:technical"])],
  [V("Le département a déjà engagé ce qu'il pouvait ; nos finances ne permettent pas d'aller plus loin."),
   V("Sans aide, le programme de rénovation s'étalera sur quinze ans : une génération entière en pâtira."),
   V("Les enseignants nous le disent : on n'apprend pas bien dans un bâtiment qui tombe en ruine."),
   V("La situation devient dangereuse dans certains établissements ; un accident n'est pas exclu.", when=["voice:blunt"]),
   V("C'est l'égalité des chances qui est en jeu, ni plus ni moins.", when=["voice:lyrical"])],
  [V("Je sollicite une aide exceptionnelle de {amountText} pour engager un plan de rénovation."),
   V("Une participation de l'État de {amountText} permettrait de traiter les situations les plus graves dès l'été prochain."),
   V("Je vous demande [[strongly]] {amountText} pour nos collèges."),
   V("Le plan, chiffré à {amountText} pour l'État, est prêt : il ne manque que votre feu vert.", when=["voice:technical"])]),
 fund_options("Rénovation des collèges ({department})", "education", 540,
              [E("quality.education", 0.004), E("scope.approval", 0.02, days=30)], {"accept": "Financer le plan de rénovation"}, groups=["young"])))

add(request("medical_desert", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Déserts médicaux : {departmentThe} tire la sonnette d'alarme",
 DEPT, (0.015, 0.05), [mod("scope.healthAccess", 0.7, 1.1, 2.5, 0.4), mod("scope.urbanShare", 0.3, 0.8, 1.4, 0.6)],
 letter("medical_desert",
  [V("Désert médical {departmentIn}"), V("Accès aux soins : notre territoire décroche"), V("Plus de médecins dans nos villages"),
   V("Appel à l'aide : la démographie médicale {departmentOf}"), V("Santé de proximité : une urgence")],
  [V("Un habitant sur {{cinq|six}} {departmentOf} n'a plus de médecin traitant."),
   V("Trois médecins généralistes partent à la retraite cette année dans notre seul canton ; aucun ne sera remplacé."),
   V("Il faut désormais {{six|huit}} mois pour obtenir un rendez-vous chez un ophtalmologiste."),
   V("Nos aînés renoncent à se soigner, faute de praticien à moins de trente kilomètres."),
   V("Les urgences de l'hôpital local servent désormais de cabinet de médecine générale."),
   V("La densité médicale du département est parmi les plus faibles du pays.", when=["voice:technical"])],
  [V("Nous avons tout essayé : primes à l'installation, logements offerts, maisons de santé. Cela ne suffit pas."),
   V("Le sentiment d'abandon progresse, et avec lui la défiance envers les institutions."),
   V("Chaque départ non remplacé fragilise un peu plus ceux qui restent."),
   V("Une famille qui s'installe demande d'abord : y a-t-il un médecin ? Nous ne pouvons plus répondre oui.", when=["voice:warm"]),
   V("On meurt plus tôt ici qu'ailleurs. C'est aussi simple et aussi grave que cela.", when=["voice:blunt"])],
  [V("Je vous demande {amountText} pour créer des centres de santé avec des médecins salariés."),
   V("Une aide de {amountText} permettrait d'ouvrir trois maisons de santé pluridisciplinaires."),
   V("L'État peut agir : {amountText} et des internes affectés chez nous changeraient tout."),
   V("Je sollicite {amountText} et, surtout, un geste fort sur l'installation des jeunes médecins.", when=["voice:formal"])]),
 fund_options("Centres de santé ({department})", "health", 450,
              [E("scope.healthAccess", 0.06), E("quality.health", 0.002), E("scope.approval", 0.03, days=30)],
              {"accept": "Financer des centres de santé"}, groups=["seniors", "rural"])))

add(request("police_reinforcement", "CITY", "MAYOR", "{city} réclame des renforts de police",
 CITY, (0.01, 0.03), [mod("scope.crime", 0.9, 1.5, 0.5, 2.5), mod("quality.security", 0.35, 0.65, 1.5, 0.6)],
 letter("police_reinforcement",
  [V("Sécurité à {city} : des renforts, vite"), V("Insécurité dans nos quartiers"), V("{city} demande plus de policiers"),
   V("Trafics et violences : la situation à {city}"), V("Ordre public à {city} : appel à l'État")],
  [V("Les points de deal se multiplient dans plusieurs quartiers de {city}."),
   V("Une série de règlements de comptes a semé la peur parmi les habitants."),
   V("Le commissariat de {city} fonctionne avec {{vingt|trente}} postes vacants."),
   V("Les commerçants du centre-ville baissent le rideau plus tôt, par crainte des agressions."),
   V("Les nuits d'été sont devenues synonymes de rodéos urbains et de dégradations.", when=["season:summer"]),
   V("Les faits de délinquance ont augmenté de {{douze|quinze}} % en un an selon les chiffres de la préfecture.", when=["voice:technical"])],
  [V("Notre police municipale fait ce qu'elle peut, mais la sécurité est une compétence de l'État."),
   V("Les habitants ont le sentiment d'être abandonnés ; certains parlent de déménager."),
   V("Si rien n'est fait, la situation risque de dégénérer."),
   V("Je refuse de voir {city} devenir une zone de non-droit.", when=["voice:blunt"]),
   V("Nos quartiers ne demandent qu'une chose : vivre en paix.", when=["voice:lyrical"])],
  [V("Je vous demande l'affectation d'une compagnie de renfort et {amountText} pour la vidéoprotection."),
   V("Des effectifs supplémentaires et une aide de {amountText} permettraient de reprendre le terrain."),
   V("Je sollicite [[strongly]] des renforts et {amountText} pour sécuriser nos quartiers.")]),
 [{"id": "reinforce", "label": "Envoyer des renforts et financer", "hint": "Coût : {amountText} ; sécurité améliorée",
   "effects": [E("budget.oneOff", param="amount"), E("scope.crime", -0.1), E("sender.relation", 0.12), E("scope.approval", 0.02, days=20), E(G + "seniors", 0.002)],
   "outcome": "ACCEPTED"},
  {"id": "temporary", "label": "Renforts temporaires seulement", "hint": "Sans coût budgétaire durable ; effet limité",
   "effects": [E("scope.crime", -0.04), E("sender.relation", 0.04)], "outcome": "PARTIAL"},
  {"id": "refuse", "label": "Renvoyer vers la police municipale", "hint": "Aucun coût ; la tension monte",
   "effects": [E("sender.relation", -0.12), E("scope.approval", -0.02, days=10), E("scope.crime", 0.03)], "outcome": "REFUSED"}],
 category="SECURITY"))

add(request("housing_shortage", "CITY", "MAYOR", "Crise du logement : {city} demande un plan de l'État",
 CITY, (0.03, 0.1), [mod("scope.populationMillions", 0.2, 1.0, 0.7, 1.6)],
 letter("housing_shortage",
  [V("Logement à {city} : la crise s'aggrave"), V("Se loger à {city} est devenu impossible"), V("Plan logement pour {city}"),
   V("Pénurie de logements : appel de {city}")],
  [V("Les loyers à {city} ont augmenté de {{vingt|vingt-cinq}} % en cinq ans."),
   V("{{Huit|Dix}} mille familles attendent un logement social dans l'agglomération."),
   V("Des salariés, des infirmières, des enseignants renoncent à des postes à {city} faute de pouvoir se loger."),
   V("Les étudiants dorment parfois dans leur voiture à la rentrée.", when=["season:autumn"]),
   V("Les meublés touristiques ont vidé le centre-ville de ses habitants.")],
  [V("Nous avons du foncier, mais pas les moyens de construire au rythme nécessaire."),
   V("Sans logement, pas d'emploi ; sans emploi, pas d'avenir pour notre jeunesse."),
   V("La crise du logement nourrit toutes les autres : pouvoir d'achat, mobilité, mal-être."),
   V("C'est la classe moyenne elle-même qui est chassée de sa ville.", when=["voice:blunt"])],
  [V("Je vous propose un plan de construction cofinancé, avec une participation de l'État de {amountText}."),
   V("{amountText} de l'État permettraient de lancer deux mille logements abordables."),
   V("Je sollicite {amountText} et la mobilisation des terrains publics inutilisés.")]),
 fund_options("Programme de logements ({city})", "housing", 900,
              [E("scope.satisfaction", 0.06), E("quality.social", 0.003), E("scope.approval", 0.02, days=30)],
              {"accept": "Lancer le programme de logements"}, groups=["young", "low_income"])))

add(request("rail_line", "DEPARTMENT", "REGION_PRESIDENT", "La région demande à l'État de sauver une petite ligne ferroviaire {departmentIn}",
 DEPT, (0.04, 0.12), [mod("quality.transport", 0.4, 0.7, 1.5, 0.7), mod("scope.urbanShare", 0.3, 0.8, 1.5, 0.6)],
 letter("rail_line",
  [V("Ligne ferroviaire menacée {departmentIn}"), V("Sauver notre petite ligne"), V("Train du quotidien : demande de la région"),
   V("Fermeture annoncée d'une ligne {departmentIn}")],
  [V("La ligne qui dessert les villages {departmentOf} est menacée de fermeture faute d'entretien."),
   V("Les trains roulent à quarante kilomètres heure sur des voies centenaires."),
   V("Chaque jour, {{mille|deux mille}} voyageurs, lycéens et salariés, empruntent cette ligne."),
   V("Le rapport de SNCF Réseau est sans appel : sans travaux, la ligne fermera dans deux ans.", when=["voice:technical"])],
  [V("Fermer cette ligne, c'est condamner des milliers de personnes à la voiture, au moment où l'on parle de transition écologique."),
   V("La région est prête à prendre sa part, mais l'infrastructure relève de l'État."),
   V("Le train, ici, c'est le lien avec le reste du pays.", when=["voice:lyrical"]),
   V("On ne peut pas parler de climat et laisser mourir le train.", when=["voice:blunt"])],
  [V("Je sollicite {amountText} pour la régénération des voies."),
   V("Avec {amountText} de l'État, la région s'engage à doubler la fréquence des trains."),
   V("Le plan de sauvetage représente {amountText} pour l'État ; c'est le prix du maintien d'un service public essentiel.")]),
 fund_options("Régénération ferroviaire ({department})", "transport", 720,
              [E("quality.transport", 0.004), E("quality.environment", 0.001), E("scope.approval", 0.02, days=30)],
              {"accept": "Financer la régénération"}, groups=["rural"])))

add(request("broadband", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Zones blanches : {departmentThe} réclame la fibre et la 5G",
 DEPT, (0.01, 0.04), [mod("scope.urbanShare", 0.3, 0.8, 1.8, 0.4)],
 letter("broadband",
  [V("Couverture numérique {departmentOf}"), V("Fibre et téléphonie : nos zones blanches"), V("Fracture numérique : appel du département"),
   V("Internet dans nos campagnes")],
  [V("Dans {{quarante|soixante}} communes {departmentOf}, on ne capte toujours pas le téléphone mobile."),
   V("Le déploiement de la fibre a pris {{trois|quatre}} ans de retard dans nos zones rurales."),
   V("Le télétravail aurait pu repeupler nos villages ; sans connexion, c'est impossible."),
   V("Les entreprises refusent de s'installer sans un débit digne de ce nom.")],
  [V("Nos habitants paient les mêmes impôts que les autres pour un service bien moindre."),
   V("La fracture numérique devient une fracture tout court."),
   V("Nos enfants font leurs devoirs sur le parking de la mairie pour avoir du réseau.", when=["voice:warm"])],
  [V("Je demande {amountText} pour achever la couverture du département."),
   V("Une participation de l'État de {amountText} permettrait de raccorder toutes les communes d'ici deux ans."),
   V("Je sollicite {amountText} et des obligations plus fermes envers les opérateurs.")]),
 fund_options("Couverture numérique ({department})", "digital", 600,
              [E("scope.unemployment", -0.002, days=120), E("scope.approval", 0.02, days=30)],
              {"accept": "Financer la couverture numérique"}, groups=["rural"])))

add(request("hospital_maternity", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Fermeture d'une maternité {departmentIn} : les élus montent au créneau",
 DEPT * 0.7, (0.01, 0.03), [mod("scope.healthAccess", 0.7, 1.1, 2.0, 0.5)],
 letter("hospital_maternity",
  [V("Maternité menacée {departmentIn}"), V("Ne fermez pas notre maternité"), V("Naître {departmentIn} : l'inquiétude"),
   V("Fermeture de maternité : appel des élus")],
  [V("L'agence régionale de santé envisage de fermer la maternité de {city}, faute de praticiens.", when=["has:city"]),
   V("L'agence régionale de santé envisage de fermer la seule maternité du secteur."),
   V("Après la fermeture, les futures mères devront parcourir plus d'une heure de route pour accoucher."),
   V("Plus de {{six cents|huit cents}} naissances ont lieu chaque année dans cet établissement.")],
  [V("Accoucher sur le bord de la route n'est pas une image : c'est déjà arrivé dans des territoires voisins."),
   V("Une maternité qui ferme, c'est une génération de familles qui part."),
   V("La mobilisation est massive : des milliers de personnes ont défilé ce week-end.")],
  [V("Je vous demande de maintenir la maternité, avec {amountText} pour recruter et sécuriser le service."),
   V("Une aide de {amountText} et un moratoire sur la fermeture : c'est tout ce que nous demandons."),
   V("Je sollicite votre intervention personnelle et {amountText}.")]),
 [{"id": "keep", "label": "Maintenir la maternité", "hint": "Coût : {amountText} par an pendant 3 ans",
   "effects": [E("sender.relation", 0.15), E("scope.approval", 0.035, days=30), E("scope.healthAccess", 0.02), E(G + "rural", 0.003)],
   "outcome": "ACCEPTED", "project": project("Maintien de la maternité ({department})", "health", 1095, 3.0, [E("quality.health", 0.001)])},
  {"id": "transform", "label": "La transformer en centre périnatal", "hint": "Compromis : suivi sur place, accouchements ailleurs",
   "effects": [E("sender.relation", -0.02), E("scope.approval", -0.01, days=15), E("budget.oneOff", param="amount", factor=0.3)], "outcome": "PARTIAL"},
  {"id": "refuse", "label": "Suivre l'avis de l'ARS", "hint": "Aucun coût ; colère locale durable",
   "effects": [E("sender.relation", -0.15), E("scope.approval", -0.04, days=30), E("scope.healthAccess", -0.03), E(G + "rural", -0.004)], "outcome": "REFUSED"}]))

add(request("flood_defense", "DEPARTMENT", "PREFECT", "Digues fragiles {departmentIn} : le préfet alerte",
 DEPT * 0.8, (0.02, 0.08), [mod("season.month", 9, 12, 1.0, 1.8)],
 letter("flood_defense",
  [V("Prévention des inondations {departmentIn}"), V("Digues : un risque majeur"), V("Note du préfet : ouvrages de protection"),
   V("Risque de crue : travaux urgents")],
  [V("Une inspection a révélé des faiblesses sur {{douze|dix-huit}} kilomètres de digues {departmentIn}."),
   V("Les ouvrages de protection datent pour certains du XIXe siècle."),
   V("{{Trente|Quarante}} mille habitants vivent dans la zone exposée en cas de rupture."),
   V("Les épisodes de pluies extrêmes se multiplient, et nos ouvrages n'ont pas été conçus pour eux.")],
  [V("En cas de crue centennale, les conséquences seraient dramatiques."),
   V("Les collectivités compétentes n'ont pas les moyens d'assumer seules ces travaux."),
   V("Je préfère vous alerter maintenant plutôt qu'après une catastrophe.")],
  [V("Je recommande un programme de confortement de {amountText}."),
   V("Le coût des travaux prioritaires est estimé à {amountText}."),
   V("Je sollicite votre arbitrage sur un plan de {amountText}, à engager avant l'hiver.")]),
 fund_options("Confortement des digues ({department})", "environment", 540,
              [E("quality.environment", 0.002), E("scope.approval", 0.01, days=20)],
              {"accept": "Engager les travaux", "refuse": "Laisser les collectivités s'en charger"}, refuse_cost=0.005),
 category="DISASTER"))

add(request("sports_facility", "CITY", "MAYOR", "{city} sollicite l'État pour un équipement sportif",
 CITY * 0.6, (0.01, 0.04), [mod("economy.growth", -0.01, 0.02, 0.6, 1.4)],
 letter("sports_facility",
  [V("Équipement sportif à {city}"), V("Une piscine pour {city}"), V("Sport pour tous à {city}"), V("Projet de complexe sportif")],
  [V("La piscine de {city} a fermé l'an dernier ; des milliers d'enfants n'apprennent plus à nager."),
   V("Nos clubs sportifs comptent {{trois|quatre}} mille licenciés pour des équipements saturés."),
   V("Le gymnase principal, construit en 1972, n'est plus aux normes."),
   V("Après le succès de nos athlètes, la demande de pratique sportive explose.")],
  [V("Le sport, c'est la santé, le lien social, la prévention de la délinquance."),
   V("Nos jeunes n'ont plus d'endroit où se retrouver le soir."),
   V("Un enfant sur deux, à l'entrée en sixième, ne sait pas nager.", when=["voice:blunt"])],
  [V("Je vous demande {amountText} pour construire un nouveau complexe aquatique et sportif."),
   V("L'État pourrait contribuer à hauteur de {amountText} ; la ville apportera le reste."),
   V("Une aide de {amountText} suffirait à lancer le chantier.")]),
 fund_options("Complexe sportif ({city})", "sport", 600,
              [E("scope.satisfaction", 0.05), E("scope.crime", -0.02), E("scope.approval", 0.015, days=30)],
              {"accept": "Financer l'équipement"}, groups=["young"], refuse_cost=0.01)))

add(request("heritage_restoration", "CITY", "MAYOR", "{city} demande de l'aide pour restaurer un monument",
 CITY * 0.5, (0.01, 0.05), [],
 letter("heritage_restoration",
  [V("Patrimoine en péril à {city}"), V("Sauver notre monument"), V("Restauration du patrimoine de {city}"), V("Un joyau menacé à {city}")],
  [V("La cathédrale de {city} présente des fissures inquiétantes ; une partie a été fermée au public."),
   V("Le beffroi, classé monument historique, menace de s'effondrer."),
   V("Le théâtre municipal, joyau du XIXe siècle, ne répond plus aux normes de sécurité."),
   V("Des pierres sont tombées de la façade de l'église Saint-{{Martin|Pierre|Étienne}} la semaine dernière.")],
  [V("Ce monument est l'âme de notre ville ; il attire chaque année des centaines de milliers de visiteurs."),
   V("Le laisser se dégrader serait une faute envers les générations futures."),
   V("Nos ancêtres l'ont bâti en deux siècles ; nous ne pouvons pas le laisser tomber en quelques années.", when=["voice:lyrical"])],
  [V("Je sollicite {amountText} pour engager la restauration."),
   V("L'État, garant du patrimoine national, pourrait apporter {amountText}."),
   V("Une souscription nationale accompagnée de {amountText} de l'État permettrait de sauver l'édifice.")]),
 fund_options("Restauration du patrimoine ({city})", "culture", 900,
              [E("scope.satisfaction", 0.05), E("scope.approval", 0.015, days=30)], {"accept": "Financer la restauration"}, refuse_cost=0.01)))

add(request("water_crisis", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Eau potable {departmentIn} : les élus réclament des investissements",
 DEPT * 0.8, (0.02, 0.06), [mod("season.month", 5, 8, 0.6, 2.0), mod("scope.mediterranean", 0, 1, 0.8, 1.8)],
 letter("water_crisis",
  [V("Ressource en eau {departmentIn}"), V("Eau potable : la situation se tend"), V("Sécheresse et réseaux : appel à l'État"), V("Nos robinets à sec")],
  [V("{{Une vingtaine|Une trentaine}} de communes {departmentOf} sont ravitaillées par camions-citernes.", when=["season:summer"]),
   V("Les nappes phréatiques sont au plus bas pour la saison."),
   V("Un litre sur cinq se perd dans des canalisations vétustes."),
   V("Les restrictions d'usage frappent agriculteurs, industriels et particuliers.")],
  [V("Sans investissements, chaque été sera pire que le précédent."),
   V("Les conflits d'usage entre agriculture, tourisme et habitants s'enveniment."),
   V("L'eau est un bien commun ; son accès ne peut pas dépendre de la richesse d'une commune.", when=["voice:lyrical"])],
  [V("Je sollicite {amountText} pour rénover les réseaux et sécuriser l'approvisionnement."),
   V("Un plan de {amountText} permettrait d'interconnecter les réseaux et de réduire les fuites."),
   V("Je vous demande {amountText}, avant le prochain été.")]),
 fund_options("Sécurisation de l'eau ({department})", "environment", 600,
              [E("quality.environment", 0.002), E("quality.agriculture", 0.001), E("scope.approval", 0.02, days=30)],
              {"accept": "Financer le plan eau"}, groups=["rural"]),
 category="DISASTER"))

add(request("industrial_zone", "DEPARTMENT", "REGION_PRESIDENT", "Implantation industrielle : la région demande l'appui de l'État {departmentIn}",
 DEPT * 0.7, (0.03, 0.1), [mod("scope.unemployment", 0.06, 0.12, 0.6, 1.8)],
 letter("industrial_zone",
  [V("Une usine pour {departmentThe} ?"), V("Projet industriel : l'État doit nous aider"), V("Réindustrialisation {departmentIn}"),
   V("Un investisseur hésite : votre soutien est décisif")],
  [V("Un groupe international envisage d'implanter une usine de batteries {departmentIn}."),
   V("Un industriel européen cherche un site pour une usine de {{panneaux solaires|composants électroniques|médicaments}}."),
   V("Le projet représenterait {{huit cents|mille deux cents}} emplois directs."),
   V("Deux autres pays européens sont en concurrence avec nous.")],
  [V("Sans un geste de l'État, l'investisseur partira ailleurs."),
   V("Notre bassin d'emploi a perdu des milliers d'emplois industriels en vingt ans ; cette chance ne repassera pas."),
   V("Les terrains sont prêts, la main-d'œuvre aussi ; il manque l'engagement national.")],
  [V("Je vous demande une aide de {amountText} pour l'aménagement du site et la formation."),
   V("L'enveloppe nécessaire est de {amountText} ; la région en apportera autant."),
   V("Avec {amountText}, nous emportons la décision.")]),
 [{"id": "support", "label": "Soutenir l'implantation", "hint": "Coût : {amountText} ; emplois et activité",
   "effects": [E("budget.oneOff", param="amount"), E("scope.unemployment", -0.006, days=360), E("scope.industry", 0.01), E("economy.businessConfidence", 0.003),
               E("sender.relation", 0.12), E("scope.approval", 0.03, days=30), E("scope.pollution", 0.03)], "outcome": "ACCEPTED"},
  {"id": "tax", "label": "Proposer des allègements fiscaux plutôt qu'une subvention", "hint": "Coût réparti, chances moindres",
   "effects": [E("budget.oneOff", param="amount", factor=0.4), E("scope.unemployment", -0.003, days=360), E("sender.relation", 0.04)], "outcome": "PARTIAL"},
  {"id": "refuse", "label": "Laisser le marché décider", "hint": "Aucun coût ; l'investisseur risque de partir",
   "effects": [E("sender.relation", -0.1), E("scope.approval", -0.02, days=15)], "outcome": "REFUSED"}],
 category="ECONOMY"))

add(request("post_office_closure", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Services publics en recul {departmentIn} : fermetures de bureaux de poste et de trésoreries",
 DEPT * 0.8, (0.005, 0.02), [mod("scope.urbanShare", 0.3, 0.8, 1.8, 0.4)],
 letter("post_office_closure",
  [V("Nos services publics disparaissent"), V("Fermetures en cascade {departmentIn}"), V("Bureaux de poste, trésoreries, gendarmeries : l'hémorragie"),
   V("Ruralité : le recul de l'État")],
  [V("En deux ans, {{neuf|douze}} bureaux de poste ont fermé ou réduit leurs horaires {departmentIn}."),
   V("La trésorerie de notre chef-lieu de canton fermera à la fin de l'année."),
   V("Les habitants doivent faire quarante kilomètres pour une simple démarche administrative."),
   V("Tout passe par internet, alors que la moitié de nos aînés n'y ont pas accès.")],
  [V("Chaque fermeture alimente le sentiment d'abandon et le vote de colère."),
   V("Le service public, c'est la présence de la République partout ; elle recule ici."),
   V("On nous ferme tout, puis on s'étonne que les gens soient en colère.", when=["voice:blunt"])],
  [V("Je vous demande un moratoire sur les fermetures et {amountText} pour ouvrir des maisons France Services."),
   V("Une enveloppe de {amountText} permettrait de maintenir une présence publique dans chaque canton."),
   V("Je sollicite votre engagement personnel et {amountText}.")]),
 fund_options("Maisons France Services ({department})", "public_services", 360,
              [E("scope.approval", 0.03, days=30), E("quality.social", 0.001)],
              {"accept": "Ouvrir des maisons France Services", "refuse": "Poursuivre la rationalisation"}, groups=["rural", "seniors"], refuse_cost=0.025)))

add(request("bridge_repair", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Pont fermé {departmentIn} : le département appelle l'État à l'aide",
 DEPT * 0.7, (0.01, 0.04), [mod("quality.transport", 0.4, 0.7, 1.6, 0.7)],
 letter("bridge_repair",
  [V("Pont fermé : un territoire coupé en deux"), V("Ouvrage d'art dangereux {departmentIn}"), V("Nos ponts s'effondrent"), V("Infrastructures routières : urgence")],
  [V("Le pont qui relie les deux rives du département a été fermé en urgence après une inspection."),
   V("Les poids lourds sont interdits sur {{trois|quatre}} ouvrages d'art jugés fragiles."),
   V("Les détours imposés rallongent les trajets quotidiens de près d'une heure."),
   V("Depuis le drame de Gênes, nous savons ce que coûte la négligence.", when=["voice:formal"])],
  [V("Les entreprises locales perdent des clients, les salariés du temps, les secours des minutes précieuses."),
   V("Le département n'a pas les moyens de reconstruire seul un tel ouvrage."),
   V("Les ambulances doivent faire un détour de vingt-cinq kilomètres.", when=["voice:blunt"])],
  [V("Je sollicite {amountText} pour la reconstruction de l'ouvrage."),
   V("L'aide de l'État, {amountText}, permettrait de rouvrir dans dix-huit mois."),
   V("Un fonds d'urgence de {amountText} est indispensable.")]),
 fund_options("Reconstruction du pont ({department})", "transport", 540,
              [E("quality.transport", 0.002), E("scope.approval", 0.02, days=30), E("scope.unemployment", -0.001, days=90)],
              {"accept": "Financer la reconstruction"})))

add(request("farmers_local", "DEPARTMENT", "PREFECT", "Agriculteurs en détresse {departmentIn} : le préfet s'inquiète",
 DEPT * 0.8, (0.01, 0.04), [mod("scope.agricultureShare", 0.02, 0.08, 0.4, 2.2), mod("quality.agriculture", 0.4, 0.7, 1.6, 0.7)],
 letter("farmers_local",
  [V("Détresse agricole {departmentIn}"), V("Note du préfet : la colère des agriculteurs"), V("Exploitations au bord du gouffre"), V("Crise agricole locale")],
  [V("Les éleveurs {departmentOf} vendent leur lait en dessous de son prix de revient depuis des mois."),
   V("La grêle a détruit une grande partie des récoltes {departmentIn}.", when=["season:summer"]),
   V("Plusieurs exploitations ont été placées en redressement judiciaire ces dernières semaines."),
   V("Le nombre de suicides d'agriculteurs inquiète profondément la mutualité sociale agricole.")],
  [V("Les syndicats agricoles menacent de bloquer les routes et la préfecture."),
   V("La détresse est réelle ; elle peut à tout moment se transformer en colère."),
   V("Sans aide, la transmission des exploitations sera compromise.")],
  [V("Je recommande un fonds d'urgence de {amountText} et un étalement des dettes sociales."),
   V("Une aide de {amountText} permettrait de passer le cap."),
   V("Je sollicite votre arbitrage sur une enveloppe de {amountText}.")]),
 [{"id": "aid", "label": "Débloquer un fonds d'urgence", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("quality.agriculture", 0.002), E("scope.approval", 0.02, days=20), E(G + "rural", 0.004), E(G + "self_employed", 0.002)],
   "outcome": "ACCEPTED"},
  {"id": "defer", "label": "Étaler les cotisations sans aide directe", "hint": "Coût limité",
   "effects": [E("budget.oneOff", param="amount", factor=0.2), E(G + "rural", 0.001)], "outcome": "PARTIAL"},
  {"id": "refuse", "label": "Renvoyer vers les aides européennes", "hint": "Aucun coût ; risque de blocages",
   "effects": [E("scope.approval", -0.02, days=15), E(G + "rural", -0.004)], "outcome": "REFUSED"}],
 category="ECONOMY"))

add(request("tourism_fund", "CITY", "MAYOR", "{city} demande un soutien pour son attractivité touristique",
 CITY * 0.4, (0.005, 0.02), [mod("season.month", 2, 5, 1.5, 0.8)],
 letter("tourism_fund",
  [V("Attractivité de {city}"), V("Tourisme : {city} a besoin de vous"), V("Un grand événement pour {city}"), V("Relancer la fréquentation de {city}")],
  [V("{city} souhaite accueillir une étape du Tour de France et un festival international."),
   V("La fréquentation touristique de {city} a reculé de {{dix|quinze}} % en deux ans."),
   V("Nos hôteliers et restaurateurs traversent une période très difficile."),
   V("Le centre historique de {city} mériterait une mise en valeur à la hauteur de son patrimoine.")],
  [V("Le tourisme fait vivre des milliers de familles ici."),
   V("Un grand événement rejaillirait sur toute la région."),
   V("Faire rayonner {city}, c'est aussi faire rayonner la France.", when=["voice:lyrical"])],
  [V("Je sollicite {amountText} pour un plan d'attractivité."),
   V("L'appui de l'État, {amountText}, serait déterminant."),
   V("Une contribution de {amountText} nous permettrait de concrétiser ce projet.")]),
 fund_options("Plan d'attractivité ({city})", "tourism", 300,
              [E("scope.satisfaction", 0.04), E("scope.unemployment", -0.001, days=90), E("scope.approval", 0.01, days=20)],
              {"accept": "Soutenir le projet"}, refuse_cost=0.005, partial=False)))

add(request("university_campus", "CITY", "MAYOR", "{city} réclame un investissement pour son université",
 CITY * 0.5, (0.03, 0.1), [mod("quality.education", 0.4, 0.7, 1.5, 0.7)], max_rank=2, template=
 letter("university_campus",
  [V("Université de {city} : un campus à bout de souffle"), V("Enseignement supérieur à {city}"), V("Nos étudiants méritent mieux"), V("Plan campus pour {city}")],
  [V("Les amphithéâtres de l'université de {city} sont saturés ; des étudiants suivent les cours assis par terre."),
   V("Les laboratoires manquent de moyens et nos chercheurs partent à l'étranger."),
   V("Les résidences étudiantes ne répondent qu'à un quart des besoins."),
   V("{{Quarante|Cinquante}} mille étudiants fréquentent notre campus, conçu pour moitié moins.")],
  [V("L'université est le moteur de notre économie locale et de l'innovation."),
   V("Sans investissement, nous perdrons nos meilleurs talents au profit des grandes métropoles."),
   V("C'est l'avenir de nos jeunes qui se joue dans ces amphithéâtres.", when=["voice:lyrical"])],
  [V("Je sollicite {amountText} pour la rénovation et l'extension du campus."),
   V("Un plan de {amountText} permettrait de construire deux mille logements étudiants et de moderniser les laboratoires."),
   V("Je vous demande {amountText} dans le cadre du prochain contrat de plan.")]),
 options=fund_options("Plan campus ({city})", "education", 900,
              [E("quality.education", 0.004), E("economy.potentialGrowth", 0.0002), E("scope.satisfaction", 0.04)],
              {"accept": "Financer le plan campus"}, groups=["young"])))

add(request("prison_overcrowding", "DEPARTMENT", "PREFECT", "Prison surpeuplée {departmentIn} : le préfet alerte",
 DEPT * 0.6, (0.02, 0.08), [mod("quality.justice", 0.3, 0.6, 1.8, 0.6)],
 letter("prison_overcrowding",
  [V("Maison d'arrêt surpeuplée {departmentIn}"), V("Note du préfet : situation pénitentiaire"), V("Prison : la situation devient explosive"), V("Surpopulation carcérale")],
  [V("La maison d'arrêt accueille près de deux fois plus de détenus que de places."),
   V("Des matelas au sol, trois détenus par cellule de neuf mètres carrés : les conditions sont indignes."),
   V("Les agressions contre les surveillants ont doublé en un an."),
   V("Le contrôleur général des lieux de privation de liberté a publié un rapport accablant.")],
  [V("Le personnel pénitentiaire est épuisé et menace de faire grève."),
   V("Une mutinerie n'est pas à exclure."),
   V("La France a déjà été condamnée par la Cour européenne des droits de l'homme pour de telles conditions.", when=["voice:formal"])],
  [V("Je recommande la construction d'un nouvel établissement, pour un coût de {amountText}."),
   V("Une extension de {amountText} permettrait de soulager la situation."),
   V("Je sollicite votre arbitrage sur un programme de {amountText}.")]),
 fund_options("Nouvel établissement pénitentiaire ({department})", "justice", 1080,
              [E("quality.justice", 0.004), E("scope.crime", -0.02)],
              {"accept": "Construire un nouvel établissement", "refuse": "Privilégier les peines alternatives"}, refuse_cost=0.005, partial=False),
 category="SECURITY"))

add(request("migrant_reception", "CITY", "MAYOR", "{city} demande l'aide de l'État pour l'accueil des personnes migrantes",
 CITY * 0.5, (0.005, 0.02), [mod("scope.populationMillions", 0.2, 1.0, 0.7, 1.5)],
 letter("migrant_reception",
  [V("Accueil des personnes migrantes à {city}"), V("Campements à {city} : la ville ne peut plus faire face"), V("Hébergement d'urgence à {city}"), V("Solidarité et responsabilité")],
  [V("Plusieurs centaines de personnes vivent dans des campements de fortune aux abords de la gare."),
   V("Nos centres d'hébergement d'urgence sont saturés depuis des mois."),
   V("Des familles avec enfants dorment dehors, malgré le froid.", when=["season:winter"]),
   V("Les associations sont à bout de souffle et réclament l'intervention de l'État.")],
  [V("La situation sanitaire des campements se dégrade dangereusement."),
   V("Les riverains s'exaspèrent et la tension monte."),
   V("L'hébergement d'urgence est une compétence de l'État ; la ville a fait plus que sa part.")],
  [V("Je vous demande {amountText} et l'ouverture de places d'hébergement supplémentaires."),
   V("Une aide de {amountText} permettrait de mettre tout le monde à l'abri."),
   V("Je sollicite une répartition plus équitable de l'accueil sur le territoire et {amountText}.")]),
 [{"id": "shelter", "label": "Ouvrir des places d'hébergement", "hint": "Coût : {amountText} ; humanitaire",
   "effects": [E("budget.oneOff", param="amount"), E("sender.relation", 0.1), E("scope.satisfaction", 0.02), E(G + "urban", 0.001)], "outcome": "ACCEPTED"},
  {"id": "spread", "label": "Répartir l'accueil dans d'autres départements", "hint": "Coût réduit ; d'autres élus protesteront",
   "effects": [E("budget.oneOff", param="amount", factor=0.5), E("sender.relation", 0.05), E("opinion.national", -0.002)], "outcome": "PARTIAL"},
  {"id": "evacuate", "label": "Évacuer les campements sans solution", "hint": "Aucun coût ; critiques des associations",
   "effects": [E("sender.relation", -0.08), E("scope.satisfaction", -0.02), E(G + "young", -0.002)], "outcome": "REFUSED"}],
 category="SECURITY", default="evacuate"))

add(request("energy_bills_local", "CITY", "MAYOR", "Factures d'énergie : {city} demande un bouclier pour ses équipements publics",
 CITY * 0.6, (0.005, 0.02), [mod("energy.priceIndex", 1.0, 1.6, 0.4, 2.5), mod("season.month", 9, 12, 1.0, 1.6)],
 letter("energy_bills_local",
  [V("Facture énergétique de {city}"), V("{city} ne peut plus payer son électricité"), V("Bouclier énergétique pour les communes"), V("Énergie : nos budgets explosent")],
  [V("La facture d'énergie de la ville a triplé en un an."),
   V("Nous avons dû fermer la piscine et baisser le chauffage dans les écoles."),
   V("L'éclairage public est désormais coupé après vingt-trois heures."),
   V("Le budget de fonctionnement de {city} ne permet plus d'absorber ces hausses.")],
  [V("Sans aide, nous devrons augmenter les impôts locaux ou réduire les services."),
   V("Ce sont les habitants qui paieront, d'une manière ou d'une autre."),
   V("Les communes n'ont pas le bouclier tarifaire dont bénéficient les ménages.")],
  [V("Je vous demande une compensation de {amountText}."),
   V("Une aide de {amountText} éviterait la fermeture de nos équipements cet hiver."),
   V("Je sollicite l'extension du bouclier tarifaire aux collectivités, soit {amountText} pour notre ville.")]),
 [{"id": "compensate", "label": "Compenser la hausse", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("sender.relation", 0.1), E("scope.satisfaction", 0.03)], "outcome": "ACCEPTED"},
  {"id": "loan", "label": "Proposer une avance remboursable", "hint": "Coût faible pour l'État",
   "effects": [E("budget.oneOff", param="amount", factor=0.2), E("sender.relation", 0.02)], "outcome": "PARTIAL"},
  {"id": "refuse", "label": "Refuser", "hint": "Aucun coût ; services locaux réduits",
   "effects": [E("sender.relation", -0.1), E("scope.satisfaction", -0.03), E("scope.approval", -0.015, days=15)], "outcome": "REFUSED"}],
 category="ENERGY"))

add(request("coastal_erosion", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Érosion du littoral {departmentIn} : des habitations menacées",
 DEPT * 0.5, (0.01, 0.04), [mod("scope.mediterranean", 0, 1, 1.0, 1.3)],
 letter("coastal_erosion",
  [V("Le littoral recule {departmentIn}"), V("Érosion côtière : des familles menacées"), V("Notre côte s'effondre"), V("Adaptation au recul du trait de côte")],
  [V("La mer a avancé de {{dix|quinze}} mètres en quelques années sur certaines plages."),
   V("Un immeuble en front de mer a dû être évacué, menacé d'effondrement."),
   V("Les tempêtes de l'hiver ont emporté des pans entiers de dune.", when=["season:winter"]),
   V("Plusieurs centaines de logements se trouvent désormais dans la zone de recul prévisible.")],
  [V("Les propriétaires ne sont pas indemnisés ; certains perdent tout."),
   V("Les communes littorales ne peuvent pas financer seules la relocalisation."),
   V("Le changement climatique n'est plus une projection : il est sous nos fenêtres.", when=["voice:lyrical"])],
  [V("Je sollicite un fonds d'adaptation de {amountText}."),
   V("Avec {amountText}, nous pourrions relocaliser les familles les plus exposées."),
   V("Je vous demande {amountText} et un cadre national pour l'indemnisation.")]),
 fund_options("Adaptation du littoral ({department})", "environment", 720,
              [E("quality.environment", 0.002), E("scope.approval", 0.02, days=30)], {"accept": "Créer un fonds d'adaptation"}),
 category="DISASTER", conditions=[{"variable": "scope.mediterranean", "min": 0.5}]))

add(request("public_transport_strike_local", "CITY", "MAYOR", "Transports urbains à {city} : la ville demande une aide d'urgence",
 CITY * 0.4, (0.005, 0.03), [mod("quality.transport", 0.4, 0.7, 1.5, 0.7)], max_rank=2, template=
 letter("public_transport_local",
  [V("Transports publics de {city}"), V("Bus et tramways : le réseau de {city} en difficulté"), V("Mobilité à {city} : appel d'urgence"), V("Le réseau de {city} au bord de la rupture")],
  [V("Le réseau de transports de {city} affiche un déficit record."),
   V("Faute de conducteurs, un bus sur cinq ne circule plus aux heures de pointe."),
   V("La fréquentation a bondi, mais les recettes ne couvrent plus les coûts."),
   V("Les rames de tramway ont plus de trente ans et tombent régulièrement en panne.")],
  [V("Sans aide, nous devrons réduire l'offre ou augmenter fortement les tarifs."),
   V("Les usagers les plus modestes seraient les premiers touchés."),
   V("Reculer sur les transports publics, c'est reculer sur le climat.")],
  [V("Je sollicite {amountText} pour maintenir et moderniser le réseau."),
   V("Une aide de {amountText} permettrait de recruter et de renouveler le matériel."),
   V("Je vous demande {amountText}.")]),
 options=fund_options("Modernisation du réseau ({city})", "transport", 540,
              [E("quality.transport", 0.002), E("scope.satisfaction", 0.04), E("quality.environment", 0.001)], {"accept": "Financer le réseau"})))

add(request("local_violence_school", "CITY", "MAYOR", "Violences aux abords d'un lycée à {city}",
 CITY * 0.4, (0.003, 0.01), [mod("scope.crime", 0.9, 1.5, 0.5, 2.0)],
 letter("school_violence",
  [V("Violences scolaires à {city}"), V("Un lycée sous tension à {city}"), V("Sécurité de nos élèves"), V("Après l'agression d'un élève à {city}")],
  [V("Un élève a été grièvement blessé lors d'une rixe aux abords du lycée."),
   V("Les enseignants ont exercé leur droit de retrait après des menaces répétées."),
   V("Les parents n'osent plus laisser leurs enfants prendre le bus scolaire."),
   V("Des bandes rivales s'affrontent régulièrement à la sortie des cours.")],
  [V("L'école doit rester un sanctuaire."),
   V("Les équipes éducatives sont désemparées et réclament du soutien."),
   V("Si nous ne faisons rien, d'autres drames suivront.", when=["voice:blunt"])],
  [V("Je vous demande des moyens supplémentaires : médiateurs, surveillants, présence policière, soit {amountText}."),
   V("Une équipe mobile de sécurité et {amountText} pour la prévention seraient nécessaires."),
   V("Je sollicite {amountText} et des effectifs dédiés.")]),
 [{"id": "team", "label": "Déployer une équipe mobile et des médiateurs", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("scope.crime", -0.03), E("quality.education", 0.001), E("sender.relation", 0.1), E(G + "middle_income", 0.001)], "outcome": "ACCEPTED"},
  {"id": "police", "label": "Renforcer seulement la présence policière", "hint": "Sans coût budgétaire",
   "effects": [E("scope.crime", -0.015), E("sender.relation", 0.03)], "outcome": "PARTIAL"},
  {"id": "refuse", "label": "Laisser l'Éducation nationale gérer", "hint": "Aucun coût",
   "effects": [E("sender.relation", -0.1), E("scope.approval", -0.015, days=15)], "outcome": "REFUSED"}],
 category="SECURITY"))

add(request("ehpad_scandal", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Maltraitance dans un EHPAD {departmentIn} : le département réclame des moyens",
 DEPT * 0.5, (0.01, 0.04), [mod("scope.seniorShare", 0.15, 0.3, 0.7, 1.6)],
 letter("ehpad_scandal",
  [V("Grand âge : après le scandale de l'EHPAD"), V("Nos aînés méritent la dignité"), V("EHPAD : appel du département"), V("Dépendance : nos établissements à bout")],
  [V("Une enquête a révélé des cas de maltraitance dans un EHPAD {departmentOf}."),
   V("Faute de personnel, des résidents restent alités toute la journée."),
   V("Les établissements du département affichent un taux d'encadrement parmi les plus bas du pays."),
   V("Les familles ont porté plainte et la presse nationale s'est emparée de l'affaire.")],
  [V("Le personnel fait ce qu'il peut, mais il est en nombre insuffisant."),
   V("Le vieillissement de la population rendra la situation intenable d'ici dix ans."),
   V("La façon dont nous traitons nos aînés dit tout de notre société.", when=["voice:lyrical"])],
  [V("Je sollicite {amountText} pour recruter des soignants et contrôler les établissements."),
   V("Un plan de {amountText} permettrait d'améliorer l'encadrement dès cette année."),
   V("Je vous demande {amountText} et une réforme du financement de la dépendance.")]),
 fund_options("Plan grand âge ({department})", "health", 360,
              [E("quality.health", 0.002), E("quality.social", 0.002), E("scope.approval", 0.02, days=30)],
              {"accept": "Lancer un plan grand âge"}, groups=["seniors"])))

add(request("forest_fire_prevention", "DEPARTMENT", "PREFECT", "Prévention des incendies {departmentIn} : le préfet demande des moyens",
 DEPT * 0.6, (0.01, 0.04), [mod("season.month", 3, 6, 0.8, 1.8), mod("scope.mediterranean", 0, 1, 0.6, 2.0)],
 letter("fire_prevention",
  [V("Avant l'été : prévention des feux de forêt"), V("Note du préfet : risque incendie"), V("Moyens de lutte contre les incendies"), V("Débroussaillement et pompiers")],
  [V("La sécheresse printanière laisse présager une saison des feux très difficile.", when=["season:spring"]),
   V("Les massifs forestiers {departmentOf} n'ont pas été débroussaillés depuis plusieurs années."),
   V("Les sapeurs-pompiers volontaires manquent et le matériel vieillit."),
   V("Les modèles de Météo-France annoncent un été plus chaud que la moyenne.")],
  [V("Une saison comme celle de 2022 serait catastrophique pour nos forêts et nos villages."),
   V("Prévenir coûte infiniment moins cher que réparer."),
   V("Je ne voudrais pas avoir à vous écrire cet été pour vous annoncer un drame.")],
  [V("Je recommande un plan de prévention de {amountText} : débroussaillement, camions, recrutement de saisonniers."),
   V("Une enveloppe de {amountText} renforcerait nos moyens dès le début de l'été."),
   V("Je sollicite votre arbitrage sur {amountText}.")]),
 [{"id": "plan", "label": "Financer le plan de prévention", "hint": "Coût : {amountText} ; risque d'incendie réduit",
   "effects": [E("budget.oneOff", param="amount"), E("quality.environment", 0.002), E("quality.security", 0.001)], "outcome": "ACCEPTED"},
  {"id": "minimal", "label": "Moyens habituels seulement", "hint": "Aucun coût supplémentaire",
   "effects": [], "outcome": "NEUTRAL"}],
 category="DISASTER", default="minimal"))

add(request("cultural_center", "CITY", "MAYOR", "{city} veut ouvrir un grand équipement culturel",
 CITY * 0.4, (0.01, 0.05), [mod("economy.growth", -0.01, 0.02, 0.6, 1.4)],
 letter("cultural_center",
  [V("Un projet culturel pour {city}"), V("Culture : {city} voit grand"), V("Médiathèque, musée, salle de spectacle : notre projet"), V("La culture pour tous à {city}")],
  [V("{city} porte un projet de grande médiathèque ouverte en soirée et le dimanche."),
   V("Nous voulons transformer une friche industrielle en lieu culturel et créatif."),
   V("Notre ville n'a pas de salle de spectacle digne de ce nom."),
   V("Un musée régional pourrait accueillir les collections aujourd'hui dans les réserves.")],
  [V("La culture est un facteur d'attractivité et de cohésion sociale."),
   V("Nos quartiers populaires sont souvent les grands oubliés de l'offre culturelle."),
   V("Une ville sans culture est une ville sans âme.", when=["voice:lyrical"])],
  [V("Je sollicite {amountText} au titre de la politique culturelle de l'État."),
   V("L'apport de l'État, {amountText}, rendrait le projet possible."),
   V("Je vous demande {amountText}.")]),
 fund_options("Équipement culturel ({city})", "culture", 720,
              [E("scope.satisfaction", 0.05), E("scope.approval", 0.01, days=30)], {"accept": "Soutenir le projet culturel"}, refuse_cost=0.005)))

add(request("road_safety", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Une route meurtrière {departmentIn} : le département demande des travaux",
 DEPT * 0.6, (0.01, 0.04), [mod("quality.transport", 0.4, 0.7, 1.5, 0.7)],
 letter("road_safety",
  [V("Route meurtrière {departmentIn}"), V("Sécurité routière : notre nationale tue"), V("Après un nouvel accident mortel"), V("Mise à deux fois deux voies : appel à l'État")],
  [V("La route nationale qui traverse le département a fait {{six|huit}} morts depuis le début de l'année."),
   V("Un nouvel accident a coûté la vie à une famille la semaine dernière."),
   V("Les poids lourds empruntent massivement cette route pour éviter les péages."),
   V("Les habitants réclament depuis vingt ans une mise à deux fois deux voies.")],
  [V("Chaque mois qui passe peut coûter de nouvelles vies."),
   V("L'État est propriétaire de cette route ; il en a la responsabilité."),
   V("Je ne veux plus assister à des obsèques de jeunes du département.", when=["voice:warm"])],
  [V("Je sollicite {amountText} pour sécuriser les tronçons les plus dangereux."),
   V("Les travaux prioritaires représentent {amountText} pour l'État."),
   V("Je vous demande {amountText} et un calendrier précis.")]),
 fund_options("Sécurisation de la route nationale ({department})", "transport", 720,
              [E("quality.transport", 0.002), E("scope.approval", 0.025, days=30)], {"accept": "Financer les travaux"})))

add(request("neighborhood_renewal", "CITY", "MAYOR", "{city} demande un programme de rénovation urbaine",
 CITY * 0.5, (0.02, 0.08), [mod("scope.crime", 0.9, 1.5, 0.7, 1.6)], max_rank=2, template=
 letter("neighborhood_renewal",
  [V("Rénovation urbaine à {city}"), V("Nos quartiers populaires attendent"), V("Un nouveau souffle pour nos quartiers"), V("Politique de la ville à {city}")],
  [V("Les tours du quartier nord de {city} n'ont pas été rénovées depuis leur construction."),
   V("Ascenseurs en panne, humidité, insalubrité : les conditions de vie sont indignes."),
   V("Le chômage des jeunes y dépasse trente pour cent."),
   V("Les commerces ferment les uns après les autres, laissant place aux trafics.")],
  [V("Ces quartiers ne demandent pas la charité, mais l'égalité."),
   V("La rénovation urbaine a montré ailleurs qu'elle pouvait transformer des vies."),
   V("Si l'on ne fait rien, les émeutes d'hier se reproduiront.", when=["voice:blunt"])],
  [V("Je sollicite {amountText} dans le cadre d'un nouveau programme de renouvellement urbain."),
   V("L'État pourrait apporter {amountText} ; bailleurs et ville feront le reste."),
   V("Je vous demande {amountText} pour redonner un avenir à ces quartiers.")]),
 options=fund_options("Renouvellement urbain ({city})", "housing", 1080,
              [E("scope.satisfaction", 0.06), E("scope.crime", -0.04), E("quality.social", 0.002), E("scope.approval", 0.02, days=30)],
              {"accept": "Lancer la rénovation urbaine"}, groups=["low_income", "urban"])))

add(request("airport_noise", "CITY", "MAYOR", "Nuisances aériennes : {city} demande des mesures",
 CITY * 0.3, (0.005, 0.02), [], max_rank=2, template=
 letter("airport_noise",
  [V("Nuisances sonores à {city}"), V("Survol de nos quartiers : les habitants à bout"), V("Bruit des avions : appel de {city}"), V("Qualité de vie et trafic aérien")],
  [V("Depuis la modification des trajectoires, des milliers d'habitants sont survolés à basse altitude."),
   V("Les vols de nuit se sont multipliés ces derniers mois."),
   V("Les associations de riverains ont déposé un recours."),
   V("Le bruit dépasse régulièrement les seuils recommandés par l'Organisation mondiale de la santé.", when=["voice:technical"])],
  [V("La santé des riverains est en jeu : sommeil, stress, maladies cardiovasculaires."),
   V("La valeur des logements s'effondre dans les quartiers survolés."),
   V("Nos habitants n'en peuvent plus.")],
  [V("Je vous demande un couvre-feu nocturne et {amountText} pour l'insonorisation des logements."),
   V("Une aide de {amountText} à l'insonorisation serait un premier pas."),
   V("Je sollicite {amountText} et une révision des trajectoires.")]),
 options=[{"id": "insulate", "label": "Financer l'insonorisation et limiter les vols de nuit", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("scope.satisfaction", 0.04), E("sender.relation", 0.1), E("economy.output", -0.00005)], "outcome": "ACCEPTED"},
  {"id": "insulate_only", "label": "Financer seulement l'insonorisation", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("scope.satisfaction", 0.02), E("sender.relation", 0.04)], "outcome": "PARTIAL"},
  {"id": "refuse", "label": "Refuser", "hint": "Aucun coût",
   "effects": [E("sender.relation", -0.08), E("scope.satisfaction", -0.02)], "outcome": "REFUSED"}]))

# ================================ Outre-mer ======================================================
OVERSEAS = [{"variable": "scope.overseas", "min": 1}]
ODEPT = 0.004  # cinq départements candidats seulement

add(request("cyclone", "DEPARTMENT", "PREFECT", "Cyclone : {departmentThe} frappé de plein fouet",
 ODEPT, (0.05, 0.2), [], 
 letter("cyclone",
  [V("Cyclone : état de catastrophe naturelle"), V("Après le passage du cyclone"), V("Ouragan : bilan et besoins"), V("Note du préfet : le cyclone")],
  [V("Le cyclone a traversé l'île avec des rafales dépassant deux cents kilomètres heure."),
   V("Des milliers de foyers sont privés d'électricité et d'eau potable."),
   V("Les routes sont coupées par les glissements de terrain ; plusieurs communes sont isolées."),
   V("Le port et l'aéroport sont fermés jusqu'à nouvel ordre.")],
  [V("Les dégâts sur les habitations et les cultures sont considérables."),
   V("L'insularité complique l'acheminement des secours et du matériel."),
   V("La population attend un geste rapide et visible de la métropole.")],
  [V("Je sollicite la reconnaissance de l'état de catastrophe naturelle et un fonds d'urgence de {amountText}."),
   V("Un pont aérien et {amountText} permettraient de rétablir les services essentiels."),
   V("Je vous demande l'envoi de renforts de la sécurité civile et {amountText}.")]),
 [{"id": "airlift", "label": "Pont aérien et fonds d'urgence", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("scope.approval", 0.05, days=30), E("sender.relation", 0.12)], "outcome": "ACCEPTED"},
  {"id": "standard", "label": "Procédure de catastrophe naturelle classique", "hint": "Coût : un tiers ; délais plus longs",
   "effects": [E("budget.oneOff", param="amount", factor=0.35), E("scope.approval", -0.02, days=20)], "outcome": "PARTIAL"}],
 category="DISASTER", conditions=OVERSEAS + [{"variable": "season.month", "oneOf": [1, 2, 3, 8, 9, 10]}], default="standard", scope_cooldown=500))

add(request("cost_of_living_overseas", "DEPARTMENT", "DEPARTMENT_PRESIDENT", "Vie chère : la colère gronde {departmentIn}",
 ODEPT, (0.02, 0.08), [mod("economy.inflation", 0.01, 0.05, 0.6, 2.0)],
 letter("cost_of_living_overseas",
  [V("Vie chère outre-mer : la situation explose"), V("Prix alimentaires : nos habitants n'en peuvent plus"), V("Barrages contre la vie chère"), V("Appel à l'État : le coût de la vie")],
  [V("Les prix alimentaires sont jusqu'à quarante pour cent plus élevés qu'en métropole."),
   V("Des barrages paralysent les principaux axes depuis plusieurs jours."),
   V("Le collectif contre la vie chère réunit syndicats, associations et élus."),
   V("Les grandes surfaces sont accusées de marges abusives.")],
  [V("Le chômage et la pauvreté rendent ces écarts de prix insupportables."),
   V("Des violences ont éclaté la nuit dernière ; la situation peut dégénérer."),
   V("Nos habitants ont le sentiment d'être des citoyens de seconde zone.")],
  [V("Je vous demande un bouclier qualité-prix renforcé et {amountText} pour baisser les prix des produits de base."),
   V("Une aide de {amountText} et une baisse de l'octroi de mer permettraient de calmer la situation."),
   V("Je sollicite votre intervention personnelle et {amountText}.")]),
 [{"id": "shield", "label": "Bouclier qualité-prix renforcé", "hint": "Coût : {amountText} ; apaisement",
   "effects": [E("budget.oneOff", param="amount"), E("scope.approval", 0.05, days=30), E("sender.relation", 0.12), E(G + "low_income", 0.002)], "outcome": "ACCEPTED"},
  {"id": "negotiate", "label": "Table ronde avec la grande distribution", "hint": "Coût faible ; effet incertain",
   "effects": [E("budget.oneOff", param="amount", factor=0.2), E("scope.approval", 0.01, days=20)], "outcome": "PARTIAL"},
  {"id": "order", "label": "Lever les barrages par la force", "hint": "Aucun coût ; colère durable",
   "effects": [E("scope.approval", -0.06, days=60), E("sender.relation", -0.15), E("scope.crime", 0.05)], "outcome": "REFUSED"}],
 category="POLITICS", conditions=OVERSEAS, default="negotiate", scope_cooldown=400))

add(request("overseas_water", "DEPARTMENT", "PREFECT", "Crise de l'eau {departmentIn} : des coupures quotidiennes",
 ODEPT * 0.7, (0.02, 0.1), [mod("scope.incomeIndex", 0.4, 0.9, 2.5, 0.5)],
 letter("overseas_water",
  [V("Crise de l'eau"), V("Coupures d'eau : la population à bout"), V("Eau potable : situation critique"), V("Note du préfet : l'eau")],
  [V("Les habitants n'ont plus d'eau au robinet qu'un jour sur deux."),
   V("Les réserves sont au plus bas après une saison sèche exceptionnelle."),
   V("Les réseaux, mal entretenus, perdent plus de la moitié de l'eau distribuée."),
   V("Des distributions de bouteilles sont organisées dans les écoles.")],
  [V("Les risques sanitaires augmentent : gastro-entérites, épidémies."),
   V("Les écoles ferment faute d'eau pour les sanitaires."),
   V("La colère de la population monte chaque jour.")],
  [V("Je recommande un plan d'urgence de {amountText} : usine de dessalement, réparation des réseaux, distribution d'eau."),
   V("Un investissement de {amountText} sécuriserait l'approvisionnement à moyen terme."),
   V("Je sollicite votre arbitrage sur {amountText}.")]),
 [{"id": "plan", "label": "Plan d'urgence et usine de dessalement", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("scope.approval", 0.04, days=30), E("scope.healthAccess", 0.03)], "outcome": "ACCEPTED"},
  {"id": "bottles", "label": "Distributions d'eau en bouteille", "hint": "Coût : un cinquième ; solution temporaire",
   "effects": [E("budget.oneOff", param="amount", factor=0.2), E("scope.approval", -0.01, days=20)], "outcome": "PARTIAL"}],
 category="DISASTER", conditions=OVERSEAS, default="bottles", scope_cooldown=600))

add(request("illegal_gold_mining", "DEPARTMENT", "PREFECT", "Orpaillage illégal : la forêt et les rivières empoisonnées {departmentIn}",
 ODEPT * 0.5, (0.01, 0.05), [mod("scope.crime", 1.0, 2.0, 0.7, 1.8)],
 letter("illegal_gold_mining",
  [V("Orpaillage illégal"), V("Garimpeiros : la situation se dégrade"), V("Sécurité et environnement en forêt"), V("Note du préfet : les sites d'orpaillage")],
  [V("Plusieurs centaines de sites d'orpaillage clandestins ont été recensés en forêt."),
   V("Le mercure utilisé contamine les rivières et les populations amérindiennes."),
   V("Des affrontements armés ont opposé gendarmes et orpailleurs la semaine dernière.")],
  [V("Les moyens militaires et de gendarmerie sont insuffisants pour couvrir un territoire aussi vaste."),
   V("Les populations du fleuve vivent dans la peur.")],
  [V("Je recommande un renforcement de l'opération de lutte, pour {amountText}."),
   V("Des moyens supplémentaires ({amountText}) permettraient de démanteler les principaux sites."),
   V("Je sollicite votre arbitrage sur {amountText}.")]),
 [{"id": "operation", "label": "Renforcer l'opération de lutte", "hint": "Coût : {amountText}",
   "effects": [E("budget.oneOff", param="amount"), E("scope.crime", -0.15), E("quality.environment", 0.001), E("scope.approval", 0.02, days=20)], "outcome": "ACCEPTED"},
  {"id": "status_quo", "label": "Maintenir les moyens actuels", "hint": "Aucun coût",
   "effects": [E("scope.crime", 0.05)], "outcome": "NEUTRAL"}],
 category="SECURITY", conditions=OVERSEAS + [{"variable": "scope.seniorShare", "max": 0.1}], default="status_quo", scope_cooldown=500))

# Demandes sans objet outre-mer (pas de réseau ferré, pas de route nationale de ce type...).
MAINLAND_ONLY = {"rail_line", "forest_fire_prevention", "flood_defense", "road_safety", "tourism_fund"}
for ev in EVENTS:
    if ev["id"] in MAINLAND_ONLY:
        ev.setdefault("conditions", []).append({"variable": "scope.overseas", "max": 0})

json.dump({"events": EVENTS}, open(os.path.join(ROOT, "events", "local.json"), "w"), ensure_ascii=False, indent=1)
json.dump({"templates": TEMPLATES}, open(os.path.join(ROOT, "dialogue", "fr", "local.json"), "w"), ensure_ascii=False, indent=1)
print(len(EVENTS), "demandes locales", len(TEMPLATES), "modèles")
